name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
    build_and_preview:
        if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci && npm run build
              env:
                  CI: true
                  REACT_APP_HASURA_LINK: ${{ secrets.REACT_APP_HASURA_LINK }}
                  REACT_APP_HASURA_PASSWORD: ${{ secrets.REACT_APP_HASURA_PASSWORD }}
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTES_ECBA8 }}'
                  projectId: notes-ecba8
                  channelId: live
